<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="9.0.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kickoffa.API.Application\Kickoffa.API.Application.csproj" />
    <ProjectReference Include="..\Kickoffa.API.AspNet.Infrastructure\Kickoffa.API.AspNet.Infrastructure.csproj" />
    <ProjectReference Include="..\Kickoffa.API.Contracts\Kickoffa.API.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mapping\" />
  </ItemGroup>

</Project>
