// <auto-generated />
using System;
using Kickoffa.API.Data.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kickoffa.API.Data.Migrations
{
    [DbContext(typeof(KickoffaDbContext))]
    [Migration("20250714235456_AddingCustomerRelationToChecklistAndCreatingTPHCustomerRelation")]
    partial class AddingCustomerRelationToChecklistAndCreatingTPHCustomerRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("ComponentSequence");

            modelBuilder.Entity("Kickoffa.API.Domain.Models.AppUser.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.AppUser.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDateUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDateUtc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastUpdatedDateUtc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.BriefingMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SectionId")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentType")
                        .HasDatabaseName("IX_BriefingMedias_ContentType");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("IX_BriefingMedias_SectionId");

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("IX_BriefingMedias_UploadedAt");

                    b.ToTable("BriefingMedias", (string)null);
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.Checklist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessToken")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(6L);

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AccessToken")
                        .IsUnique()
                        .HasDatabaseName("IX_Checklists_AccessToken");

                    b.HasIndex("CustomerId");

                    b.HasIndex("AccessToken", "OwnerId")
                        .HasDatabaseName("IX_Checklists_AccessToken_OwnerId")
                        .HasFilter("\"IsPublished\" = true");

                    b.HasIndex("OwnerId", "CreatedDateUtc")
                        .HasDatabaseName("IX_Checklists_OwnerId_CreatedDateUtc");

                    b.HasIndex("OwnerId", "CustomerId")
                        .HasDatabaseName("IX_Checklists_OwnerId_CustomerId");

                    b.HasIndex("OwnerId", "IsPublished")
                        .HasDatabaseName("IX_Checklists_OwnerId_IsPublished");

                    b.HasIndex("OwnerId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Checklists_OwnerId_Slug");

                    b.ToTable("Checklists", (string)null);
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.Components.Base.Component", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"ComponentSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<long>("SectionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.Components.ComponentStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ComponentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Response")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId")
                        .IsUnique()
                        .HasDatabaseName("IX_ComponentStatuses_ComponentId");

                    b.HasIndex("IsCompleted")
                        .HasDatabaseName("IX_ComponentStatuses_IsCompleted");

                    b.ToTable("ComponentStatuses", (string)null);
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.Components.FileType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("RecommendedMaxSizeMB")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_FileTypes_Category");

                    b.HasIndex("Extension")
                        .HasDatabaseName("IX_FileTypes_Extension");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_FileTypes_IsActive");

                    b.HasIndex("MimeType")
                        .HasDatabaseName("IX_FileTypes_MimeType");

                    b.HasIndex("Category", "DisplayOrder")
                        .HasDatabaseName("IX_FileTypes_Category_DisplayOrder");

                    b.HasIndex("MimeType", "Extension")
                        .IsUnique()
                        .HasDatabaseName("IX_FileTypes_MimeType_Extension");

                    b.ToTable("FileTypes", (string)null);
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.Components.UploadComponentFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("UploadComponentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FileName")
                        .HasDatabaseName("IX_UploadComponentFiles_FileName");

                    b.HasIndex("Sha256Hash")
                        .HasDatabaseName("IX_UploadComponentFiles_Sha256Hash");

                    b.HasIndex("UploadComponentId")
                        .HasDatabaseName("IX_UploadComponentFiles_UploadComponentId");

                    b.HasIndex("Id", "CreatedDateUtc")
                        .HasDatabaseName("IX_UploadComponentFiles_UploadComponentId_CreatedDateUtc");

                    b.ToTable("UploadComponentFiles", (string)null);
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.Components.UploadComponentFileTypeSize", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxSizeMB")
                        .HasColumnType("integer");

                    b.Property<long>("UploadComponentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FileTypeId");

                    b.HasIndex("UploadComponentId");

                    b.HasIndex("UploadComponentId", "FileTypeId")
                        .IsUnique();

                    b.HasIndex("UploadComponentId", "FileTypeId", "MaxSizeMB");

                    b.ToTable("UploadComponentFileTypeSizes", (string)null);
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.FreelancerCustomer.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("Address");

                    b.Property<DateTime>("CreatedDateUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDateUtc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Email");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastUpdatedDateUtc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("OwnerId");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("PhoneNumber");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.ToTable("Customers", (string)null);

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.Section", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChecklistId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("SectionType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId")
                        .HasDatabaseName("IX_Sections_ChecklistId");

                    b.HasIndex("SectionType")
                        .HasDatabaseName("IX_Sections_SectionType");

                    b.HasIndex("ChecklistId", "Order")
                        .HasDatabaseName("IX_Sections_ChecklistId_Order");

                    b.ToTable("Sections", (string)null);

                    b.HasDiscriminator<string>("SectionType").HasValue("Section");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UploadComponentAllowedFileTypes", b =>
                {
                    b.Property<long>("AllowedFileTypesId")
                        .HasColumnType("bigint");

                    b.Property<long>("UploadComponentId")
                        .HasColumnType("bigint");

                    b.HasKey("AllowedFileTypesId", "UploadComponentId");

                    b.HasIndex("UploadComponentId");

                    b.ToTable("UploadComponentAllowedFileTypes");
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.Components.CheckboxComponent", b =>
                {
                    b.HasBaseType("Kickoffa.API.Domain.Models.Components.Base.Component");

                    b.HasIndex("IsRequired")
                        .HasFilter("\"IsRequired\" = true");

                    b.HasIndex("SectionId", "IsRequired");

                    b.HasIndex("SectionId", "Order");

                    b.ToTable("CheckboxComponents", (string)null);
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.Components.ConfirmationComponent", b =>
                {
                    b.HasBaseType("Kickoffa.API.Domain.Models.Components.Base.Component");

                    b.Property<string>("ConfirmationText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasIndex("ConfirmationText");

                    b.HasIndex("SectionId", "ConfirmationText");

                    b.HasIndex("SectionId", "Order");

                    b.ToTable("ConfirmationComponents", (string)null);
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.Components.SignatureComponent", b =>
                {
                    b.HasBaseType("Kickoffa.API.Domain.Models.Components.Base.Component");

                    b.HasIndex("IsRequired")
                        .HasFilter("\"IsRequired\" = true");

                    b.HasIndex("SectionId", "IsRequired");

                    b.HasIndex("SectionId", "Order");

                    b.HasIndex("SectionId", "IsRequired", "Order");

                    b.ToTable("SignatureComponents", (string)null);
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.Components.TextComponent", b =>
                {
                    b.HasBaseType("Kickoffa.API.Domain.Models.Components.Base.Component");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("integer");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasIndex("MaxLength");

                    b.HasIndex("Placeholder");

                    b.HasIndex("SectionId", "Order");

                    b.HasIndex("SectionId", "Placeholder");

                    b.ToTable("TextComponents", (string)null);
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.Components.UploadComponent", b =>
                {
                    b.HasBaseType("Kickoffa.API.Domain.Models.Components.Base.Component");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasIndex("Placeholder");

                    b.HasIndex("SectionId", "Order");

                    b.ToTable("UploadComponents", (string)null);
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.FreelancerCustomer.LegalPerson", b =>
                {
                    b.HasBaseType("Kickoffa.API.Domain.Models.FreelancerCustomer.Customer");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("Cnpj");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Company");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasFilter("\"Cnpj\" IS NOT NULL AND \"Type\" = 2");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.FreelancerCustomer.NaturalPerson", b =>
                {
                    b.HasBaseType("Kickoffa.API.Domain.Models.FreelancerCustomer.Customer");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("Cpf");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("LastName");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasFilter("\"Cpf\" IS NOT NULL AND \"Type\" = 1");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.BriefingSection", b =>
                {
                    b.HasBaseType("Kickoffa.API.Domain.Models.Section");

                    b.Property<string>("ContentHtml")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ContentLastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("Briefing");
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.ChecklistSection", b =>
                {
                    b.HasBaseType("Kickoffa.API.Domain.Models.Section");

                    b.HasDiscriminator().HasValue("Checklist");
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.BriefingMedia", b =>
                {
                    b.HasOne("Kickoffa.API.Domain.Models.BriefingSection", "Section")
                        .WithMany("Media")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.Checklist", b =>
                {
                    b.HasOne("Kickoffa.API.Domain.Models.FreelancerCustomer.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.Components.Base.Component", b =>
                {
                    b.HasOne("Kickoffa.API.Domain.Models.ChecklistSection", "Section")
                        .WithMany("Components")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.Components.ComponentStatus", b =>
                {
                    b.HasOne("Kickoffa.API.Domain.Models.Components.Base.Component", "Component")
                        .WithOne("Status")
                        .HasForeignKey("Kickoffa.API.Domain.Models.Components.ComponentStatus", "ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.Components.UploadComponentFile", b =>
                {
                    b.HasOne("Kickoffa.API.Domain.Models.Components.UploadComponent", "UploadComponent")
                        .WithMany("ComponentFiles")
                        .HasForeignKey("UploadComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UploadComponent");
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.Components.UploadComponentFileTypeSize", b =>
                {
                    b.HasOne("Kickoffa.API.Domain.Models.Components.FileType", "FileType")
                        .WithMany()
                        .HasForeignKey("FileTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kickoffa.API.Domain.Models.Components.UploadComponent", "UploadComponent")
                        .WithMany("FileTypeSizeConfigs")
                        .HasForeignKey("UploadComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileType");

                    b.Navigation("UploadComponent");
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.Section", b =>
                {
                    b.HasOne("Kickoffa.API.Domain.Models.Checklist", "Checklist")
                        .WithMany("Sections")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checklist");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Kickoffa.API.Domain.Models.AppUser.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("Kickoffa.API.Domain.Models.AppUser.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("Kickoffa.API.Domain.Models.AppUser.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Kickoffa.API.Domain.Models.AppUser.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kickoffa.API.Domain.Models.AppUser.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("Kickoffa.API.Domain.Models.AppUser.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UploadComponentAllowedFileTypes", b =>
                {
                    b.HasOne("Kickoffa.API.Domain.Models.Components.FileType", null)
                        .WithMany()
                        .HasForeignKey("AllowedFileTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kickoffa.API.Domain.Models.Components.UploadComponent", null)
                        .WithMany()
                        .HasForeignKey("UploadComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.Checklist", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.Components.Base.Component", b =>
                {
                    b.Navigation("Status");
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.Components.UploadComponent", b =>
                {
                    b.Navigation("ComponentFiles");

                    b.Navigation("FileTypeSizeConfigs");
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.BriefingSection", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("Kickoffa.API.Domain.Models.ChecklistSection", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
